name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  blog-deploy:
    name: Deploy Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/deploy-cloudflare-pages
        with:
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          working-directory: web
          project-name: blog
          output-directory: public
